version: '3'

services:
  front:
    build: ./front
    ports:
      - 8080:8080
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    depends_on:
      - es01
      - es02
  users:
    build: ./users
    volumes: 
      - ./users:/usr/src/app/users
    command: python3 server.py
    ports:
      - 5001:5001

  groups:
    build: ./groups
    volumes:
      - ./groups:/usr/src/app/groups
    command: python3 server.py
    ports:
      - 5002:5002
    depends_on:
      - redis

  dates:
    build: ./dates
    volumes:
      - ./dates:/usr/src/app/dates
    command: python3 server.py
    expose:
      - 5003
    depends_on:
      - redis

  worker:
    build: ./worker
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    depends_on:
      - redis

  redis:
    image: redis:4.0.11-alpine
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    expose:
      - 9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
  varnish:
    image: varnish:6.3
    environment:
      - "VARNISH_CONFIG=/etc/varnish/default.vcl"
    volumes:
      - ./varnish/test/default.vcl:/etc/varnish/default.vcl
    expose:
      - 6081
    depends_on:
      - dates
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
#  nginx:
#    image: nginx:1.17.7
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    expose:
#      - "5003"
#    depends_on:
#      - front
    
